export interface SystemKnowledgeBaseEntry {
  id: string;
  topic: string;
  category: 'infrastructure' | 'capability' | 'constraint' | 'agent';
  content: string;
  version: number;
  metadata?: Record<string, unknown>;
}

export const SYSTEM_KNOWLEDGE_BASE: SystemKnowledgeBaseEntry[] = [
  {
    id: 'directory_structure',
    topic: '数据目录结构',
    category: 'infrastructure',
    version: 1,
    content: `## Cabinet 数据目录结构
用户数据根目录：\`~/.cabinet\`（跨平台，通过 os.homedir() 解析）

子目录：
- \`skills/\` — 技能目录。每个技能一个子文件夹，内含 SKILL.md。API: /api/skills
- \`agents/\` — 自定义 Agent 目录。每个 Agent 一个子文件夹，内含 agent.json。API: /api/agents
- \`projects/\` — 项目索引目录。JSON 文件描述项目元数据。
- \`mcp/\` — MCP 服务器配置文件（*.json）。
- \`backups/\` — 数据库自动备份。
- \`logs/\` — 日志文件（pino-roll 管理，10MB 轮转）。
- \`sessions/\` — 会话持久化数据。
- \`plans/\` — 计划文件。
- \`rules/\` — 规则文件。

**重要**：所有用户数据操作必须基于上述路径，禁止硬编码其他路径。`,
  },
  {
    id: 'scheduler_capabilities',
    topic: '定时调度器',
    category: 'capability',
    version: 1,
    content: `## 内置定时调度器
Cabinet 内置基于 node-cron 的定时任务调度器，支持标准 5 字段 cron 表达式。

可用工具：
- \`schedule_task(name, cron, prompt, recurring)\` — 创建定时任务。\`cron\` 参数使用标准 cron 表达式，如：
  - \`*/5 * * * *\` — 每 5 分钟
  - \`0 9 * * *\` — 每天 9:00
  - \`0 0 * * 0\` — 每周日午夜
- \`list_scheduled_tasks\` — 列出所有活跃任务
- \`cancel_scheduled_task(taskId)\` — 取消任务

任务持久化到 SQLite，server 重启后自动恢复。`,
  },
  {
    id: 'agent_responsibilities',
    topic: 'Agent 分工',
    category: 'agent',
    version: 1,
    content: `## Agent 职责边界
- **secretary** — 入口路由、通用对话、意图识别、工具分发
- **organize** — 首席组织架构师。将业务目标转化为 Agent + Workflow 蓝图。统筹设计，不直接执行具体流程。
- **workflow_designer** — 流程设计师。设计多步骤自动化流程（WorkflowDefinition JSON）。不负责创建新 Agent。
- **curator** — 记忆管理员。会话总结、知识固化、模式提取、项目进度跟踪。
- **decision_analyst** — 决策分析师。结构化分析、选项评估、风险权衡。
- **meeting_chair** — 会议主持人。多视角辩论、共识合成。
- **reviewer** — 质量审查员。逻辑、证据、完整性检查。

**路由原则**：
- 涉及"设计体系/创建 Agent/组织架构" → organize
- 涉及"设计流程/步骤自动化" → workflow_designer
- 涉及"总结/记忆/进度" → curator
- 不确定 → secretary`,
  },
  {
    id: 'system_constraints',
    topic: '系统约束',
    category: 'constraint',
    version: 1,
    content: `## 系统架构约束
- **本地优先**：所有数据存储在本地 SQLite，不依赖外部云服务。
- **零外部依赖**：除 LLM API 调用外，核心功能完全离线运行。
- **单机架构**：当前为单机桌面应用，不支持多租户。
- **安全分级**：T0（完全审查）→ T1（策略守护）→ T2（操作监管）→ T3（完全自主）。
- **预算控制**：内置日/周/月预算限制，超预算时 LLM 调用受控。`,
  },
  {
    id: 'available_tools_overview',
    topic: '可用工具概览',
    category: 'capability',
    version: 1,
    content: `## 核心工具类别
- **文件操作**：read_file, write_file, edit_file, list_directory, search_files
- **记忆管理**：remember, recall, search_memory, write_memory
- **决策流程**：create_decision, query_decisions, get_decision
- **工作流**：create_workflow, run_workflow, list_workflows
- **Agent 管理**：register_agent, list_agents, update_agent
- **调度**：schedule_task, list_scheduled_tasks, cancel_scheduled_task
- **会议**：start_meeting
- **项目**：get_project_context, update_project_summary
- **系统知识查询**：query_system_knowledge, get_system_knowledge`,
  },
];

import { SystemKnowledgeRepository } from './repositories/system-knowledge-repo.js';

export function syncSystemKnowledge(
  db: import('better-sqlite3').Database,
  baseEntries: SystemKnowledgeBaseEntry[],
): { created: number; updated: number } {
  const repo = new SystemKnowledgeRepository(db);
  repo.ensureTable();

  let created = 0;
  let updated = 0;

  for (const entry of baseEntries) {
    const currentVersion = repo.getVersion(entry.id);
    if (currentVersion === 0) {
      repo.upsert({
        ...entry,
        metadata: JSON.stringify(entry.metadata ?? { source: 'code', autoGenerated: true }),
      });
      created++;
    } else if (entry.version > currentVersion) {
      repo.upsert({
        ...entry,
        metadata: JSON.stringify(entry.metadata ?? { source: 'code', autoGenerated: true }),
      });
      updated++;
    }
  }

  return { created, updated };
}
