from __future__ import annotations

from typing import Protocol, runtime_checkable

from cabinet.models.primitives import MemoryItem, MemoryScope


@runtime_checkable
class MemoryStore(Protocol):
    async def store(self, key: str, value: MemoryItem, scope: MemoryScope) -> None: ...
    async def retrieve(self, key: str, scope: MemoryScope) -> MemoryItem | None: ...
    async def search(self, query: str, scope: MemoryScope, limit: int = 5) -> list[MemoryItem]: ...
    async def delete(self, key: str, scope: MemoryScope) -> None: ...
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
