/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Semantic surface tokens — auto-switch via CSS variables
        surface: {
          primary: 'var(--surface-primary)',
          elevated: 'var(--surface-elevated)',
          overlay: 'var(--surface-overlay)',
          input: 'var(--surface-input)',
          muted: 'var(--surface-muted)',
          sidebar: 'var(--surface-sidebar)',
        },
        // Semantic content/text tokens
        content: {
          primary: 'var(--content-primary)',
          secondary: 'var(--content-secondary)',
          tertiary: 'var(--content-tertiary)',
          inverse: 'var(--content-inverse)',
        },
        // Semantic border tokens
        border: {
          DEFAULT: 'var(--border-color)',
          subtle: 'var(--border-subtle)',
        },
        // Accent / brand tokens
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          muted: 'var(--accent-muted)',
          foreground: 'var(--accent-foreground)',
        },
        // Intent / semantic color tokens
        intent: {
          success: 'var(--intent-success)',
          'success-muted': 'var(--intent-success-muted)',
          'success-foreground': 'var(--intent-success-foreground)',
          danger: 'var(--intent-danger)',
          'danger-muted': 'var(--intent-danger-muted)',
          'danger-foreground': 'var(--intent-danger-foreground)',
          warning: 'var(--intent-warning)',
          'warning-muted': 'var(--intent-warning-muted)',
          'warning-foreground': 'var(--intent-warning-foreground)',
          info: 'var(--intent-info)',
          'info-muted': 'var(--intent-info-muted)',
          'info-foreground': 'var(--intent-info-foreground)',
          purple: 'var(--intent-purple)',
          'purple-muted': 'var(--intent-purple-muted)',
          'purple-foreground': 'var(--intent-purple-foreground)',
        },
        // Code block tokens
        code: {
          'block-bg': 'var(--code-block-bg)',
          'block-border': 'var(--code-block-border)',
          'block-color': 'var(--code-block-color)',
          'inline-bg': 'var(--code-inline-bg)',
          'inline-color': 'var(--code-inline-color)',
        },
        // Syntax highlighting tokens
        syntax: {
          keyword: 'var(--syntax-keyword)',
          string: 'var(--syntax-string)',
          number: 'var(--syntax-number)',
          comment: 'var(--syntax-comment)',
          function: 'var(--syntax-function)',
          variable: 'var(--syntax-variable)',
          tag: 'var(--syntax-tag)',
        },
        // Graph visualization tokens
        graph: {
          'entity-person': 'var(--graph-entity-person)',
          'entity-project': 'var(--graph-entity-project)',
          'entity-concept': 'var(--graph-entity-concept)',
          'entity-technology': 'var(--graph-entity-technology)',
          'entity-decision': 'var(--graph-entity-decision)',
          'entity-memory': 'var(--graph-entity-memory)',
          'edge-active': 'var(--graph-edge-active)',
          'edge-inactive': 'var(--graph-edge-inactive)',
          'node-label': 'var(--graph-node-label)',
          'bg-grid': 'var(--graph-bg-grid)',
          'minimap-mask': 'var(--graph-minimap-mask)',
        },
        // Chart / data-viz palette
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
          '6': 'var(--chart-6)',
          '7': 'var(--chart-7)',
          '8': 'var(--chart-8)',
        },
      },
      borderRadius: {
        DEFAULT: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-xl)',
        '3xl': 'var(--radius-xl)',
        'ui-sm': 'var(--radius-sm)',
        'ui-md': 'var(--radius-md)',
        'ui-lg': 'var(--radius-lg)',
        'ui-xl': 'var(--radius-xl)',
      },
      boxShadow: {
        DEFAULT: 'var(--shadow-sm)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-lg)',
        '2xl': 'var(--shadow-lg)',
      },
      borderWidth: {
        DEFAULT: 'var(--border-width)',
        0: '0px',
        2: '2px',
        3: '3px',
        4: '4px',
      },
      borderStyle: {
        DEFAULT: 'var(--border-style)',
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: '1rem' }],
        sm: ['var(--font-size-sm)', { lineHeight: '1.25rem' }],
        base: ['var(--font-size-base)', { lineHeight: '1.5rem' }],
        lg: ['var(--font-size-lg)', { lineHeight: '1.75rem' }],
        xl: ['var(--font-size-xl)', { lineHeight: '1.75rem' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: '2rem' }],
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        '3xs': ['0.6875rem', { lineHeight: '0.875rem' }],
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        bold: 'var(--font-weight-bold)',
      },
      transitionDuration: {
        DEFAULT: 'var(--duration)',
        75: '75ms',
        100: '100ms',
        150: 'var(--duration)',
        200: 'var(--duration)',
        300: 'var(--duration)',
        500: 'var(--duration)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--easing)',
      },
      fontFamily: {
        sans: 'var(--font-family)',
        mono: 'var(--font-family)',
        serif: 'var(--font-family)',
        display: 'var(--font-display)',
      },
      opacity: {
        0: '0',
        5: '0.05',
        10: '0.1',
        20: '0.2',
        25: '0.25',
        30: '0.3',
        40: '0.4',
        50: '0.5',
        60: '0.6',
        70: '0.7',
        75: '0.75',
        80: '0.8',
        90: '0.9',
        95: '0.95',
        100: '1',
      },
      blur: {
        DEFAULT: 'var(--blur-amount)',
      },
      backdropBlur: {
        DEFAULT: 'var(--blur-amount)',
      },
    },
  },
  plugins: [],
};
