from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from cabinet.models.decisions import Decision
from cabinet.models.events import DecisionRequest
from cabinet.rooms.decision.models import (
    AuthorizationRule,
    AuthorizationVerdict,
    DecisionDashboard,
)


@runtime_checkable
class DecisionRoom(Protocol):
    async def submit(self, request: DecisionRequest) -> Decision: ...
    async def approve(self, decision_id: UUID, option: dict) -> Decision: ...
    async def reject(self, decision_id: UUID, reason: str) -> Decision: ...
    async def delegate(self, decision_id: UUID, delegate_to: str) -> Decision: ...
    async def get_dashboard(self, project_id: UUID) -> DecisionDashboard: ...
    async def set_authorization(self, rule: AuthorizationRule) -> None: ...
    async def check_authorization(self, decision: Decision) -> AuthorizationVerdict: ...
    async def cascade(self, decision: Decision) -> list[Decision]: ...
